FOOT_LEFT = 0
FOOT_RIGHT = 1
KNEE_LEFT = 2
KNEE_RIGHT = 3
HIP_LEFT = 4
HIP_RIGHT = 5
HAND_LEFT = 6
HAND_RIGHT = 7
ELBOW_LEFT = 8
ELBOW_RIGHT = 9
SHOULDER_LEFT = 10
SHOULDER_RIGHT = 11
HEAD = 12
HIP = 13
NECK = 14

ROOT_JOINT = NECK

ANGLE_KNEE_LEFT = [FOOT_LEFT, KNEE_LEFT, HIP_LEFT]
ANGLE_KNEE_RIGHT = [FOOT_RIGHT, KNEE_RIGHT, HIP_RIGHT]
ANGLE_HIP_LEFT = [KNEE_LEFT, HIP_LEFT, HIP_RIGHT]
ANGLE_HIP_RIGHT = [KNEE_RIGHT, HIP_RIGHT, HIP_LEFT]
ANGLE_ELBOW_LEFT = [HAND_LEFT, ELBOW_LEFT, SHOULDER_LEFT]
ANGLE_ELBOW_RIGHT = [HAND_RIGHT, ELBOW_RIGHT, SHOULDER_RIGHT]
ANGLE_SHOULDER_LEFT = [ELBOW_LEFT, SHOULDER_LEFT, SHOULDER_RIGHT]
ANGLE_SHOULDER_RIGHT = [ELBOW_RIGHT, SHOULDER_RIGHT, SHOULDER_LEFT]
